# -*- coding: utf-8 -*-
"""Nyári Tanoda 2026 – tananyag-adatbázis (Anna 7,5 év + Lotti 4,5 év)."""

NAPOK = ["hétfő", "kedd", "szerda", "csütörtök", "péntek", "szombat", "vasárnap"]
HONAPOK = ["január", "február", "március", "április", "május", "június",
           "július", "augusztus", "szeptember", "október", "november", "december"]

# ---------------------------------------------------------------- HETI TÉMÁK
# (kezdőnap-index szerint, 0 = 2026-07-06 hétfő)
TEMAK = [
    dict(nev="Háziállatok és a nyár", emoji="🐶",
         angol_tema="Pets / Háziállatok",
         angol=[("dog", "kutya"), ("cat", "macska"), ("rabbit", "nyúl"),
                ("bird", "madár"), ("fish", "hal"), ("horse", "ló"),
                ("hen", "tyúk"), ("pig", "malac")],
         lotti_allat=["kutya", "cica", "nyuszi", "malac", "tyúk", "ló", "kecske"]),
    dict(nev="Az erdő állatai", emoji="🦊",
         angol_tema="Forest animals / Erdei állatok",
         angol=[("fox", "róka"), ("bear", "medve"), ("owl", "bagoly"),
                ("deer", "őz"), ("squirrel", "mókus"), ("hedgehog", "sün"),
                ("wolf", "farkas"), ("tree", "fa")],
         lotti_allat=["róka", "mókus", "sün", "bagoly", "őzike", "medve", "nyuszi"]),
    dict(nev="Vízpart és vízi állatok", emoji="🐸",
         angol_tema="Water animals / Vízi állatok",
         angol=[("frog", "béka"), ("duck", "kacsa"), ("swan", "hattyú"),
                ("water", "víz"), ("boat", "csónak"), ("sun", "nap"),
                ("beach", "strand"), ("swim", "úszik")],
         lotti_allat=["béka", "kacsa", "hattyú", "halacska", "csiga", "gólya", "szitakötő"]),
    dict(nev="A testünk és az egészség", emoji="🍎",
         angol_tema="My body / A testem",
         angol=[("head", "fej"), ("hand", "kéz"), ("leg", "láb"),
                ("eye", "szem"), ("ear", "fül"), ("nose", "orr"),
                ("mouth", "száj"), ("hair", "haj")],
         lotti_allat=["maci (mutasd a fejét!)", "baba", "orvos", "fogtündér",
                      "szemüveges bagoly", "fogkefe-manó", "vitamin-nyuszi"]),
    dict(nev="Növények és a kert", emoji="🌻",
         angol_tema="Garden / A kert",
         angol=[("flower", "virág"), ("apple", "alma"), ("pear", "körte"),
                ("carrot", "répa"), ("tomato", "paradicsom"), ("grass", "fű"),
                ("seed", "mag"), ("garden", "kert")],
         lotti_allat=["katicabogár", "méhecske", "pillangó", "giliszta", "csiga",
                      "hangya", "szöcske"]),
    dict(nev="Időjárás és évszakok", emoji="🌦️",
         angol_tema="Weather / Időjárás",
         angol=[("sunny", "napos"), ("rainy", "esős"), ("windy", "szeles"),
                ("cloud", "felhő"), ("snow", "hó"), ("hot", "meleg"),
                ("cold", "hideg"), ("rainbow", "szivárvány")],
         lotti_allat=["esőfelhő", "napocska", "szivárvány", "hóember", "szélforgó",
                      "esernyős kacsa", "villám"]),
    dict(nev="Közlekedés", emoji="🚗",
         angol_tema="Transport / Közlekedés",
         angol=[("car", "autó"), ("bus", "busz"), ("train", "vonat"),
                ("bike", "bicikli"), ("plane", "repülő"), ("ship", "hajó"),
                ("stop", "állj"), ("go", "menj")],
         lotti_allat=["autó", "vonat", "repülő", "hajó", "bicikli", "mentőautó", "tűzoltóautó"]),
    dict(nev="A világűr és a Föld", emoji="🚀",
         angol_tema="Space / Világűr",
         angol=[("sun", "Nap"), ("moon", "Hold"), ("star", "csillag"),
                ("Earth", "Föld"), ("rocket", "rakéta"), ("sky", "ég"),
                ("planet", "bolygó"), ("night", "éjszaka")],
         lotti_allat=["rakéta", "csillag", "holdacska", "űrhajós", "bolygó",
                      "üstökös", "napocska"]),
    dict(nev="Irány az iskola és az ovi! – Nagy ismétlés", emoji="🎒",
         angol_tema="School / Iskola",
         angol=[("school", "iskola"), ("book", "könyv"), ("pen", "toll"),
                ("bag", "táska"), ("friend", "barát"), ("teacher", "tanító"),
                ("read", "olvas"), ("write", "ír")],
         lotti_allat=["iskolatáska", "ceruza", "radír", "könyv", "uzsonnás doboz",
                      "óvodai jel", "csengő"]),
]

# ------------------------------------------------- ANNA – NYELVTAN (57 nap)
ANNA_NYELVTAN = [
    # 1. hét – ábécé, magánhangzók
    ("Az ábécé", "Írd le az ábécé első 10 betűjét szép sorban! Utána mondd fel az egészet fejből!"),
    ("Magánhangzók", "Karikázd be a magánhangzókat: k, a, s, e, t, i, m, o, r, ö, l, u! Hány darabot találtál?"),
    ("Betűrend", "Tedd betűrendbe: kutya, alma, ház, eper, ló! Írd le őket sorban!"),
    ("Magánhangzó-vadászat", "Írd le 5 háziállat nevét, és húzd alá bennük a magánhangzókat!"),
    ("Ábécé-játék", "Írj egy-egy szót, ami A, B, C, D és E betűvel kezdődik!"),
    ("Hétvégi másolás", "Másold le szépen: A kutya hűséges barát."),
    ("Vasárnapi mese", "Kérj meg valakit, hogy olvasson fel egy rövid mesét! Mondd el a saját szavaiddal, miről szólt!"),
    # 2. hét – rövid és hosszú magánhangzók
    ("Rövid–hosszú", "Írd le párban: o–ó, u–ú, i–í! Mondd ki őket hangosan, figyeld a különbséget!"),
    ("Melyik a helyes?", "Karikázd be a helyeset: róka / roka, sün / sűn, őz / öz, bagoly / bágoly!"),
    ("Hosszú magánhangzók", "Gyűjts 5 szót, amiben hosszú ó van! (Például: hajó...)"),
    ("Pótold a betűt!", "Pótold: r_ka (róka), m_kus (mókus), erd_ (erdő), _z (őz)! Írd le a teljes szavakat!"),
    ("Szópárok", "Mit jelent? kor – kór, öt – őt, tőr – tör. Mondj mindegyikkel egy mondatot!"),
    ("Hétvégi másolás", "Másold le szépen: Az erdőben sok mókus ugrál."),
    ("Vasárnapi játék", "Szólánc: mondj egy állatot, a következő játékos olyan szót mond, ami az utolsó betűvel kezdődik!"),
    # 3. hét – mássalhangzók, szótagolás
    ("Mássalhangzók", "Húzd alá a mássalhangzókat: béka, kacsa, hattyú! Számold meg, melyikben van a legtöbb!"),
    ("Kétjegyű betűk", "Írd le a kétjegyű betűket: gy, ny, sz, ty, zs, cs, ly! Írj egy szót, amiben cs van!"),
    ("Szótagolás", "Tapsold és írd le szótagolva: ka-csa, hat-tyú, csó-nak, szi-vár-vány!"),
    ("Hány szótag?", "Írd a szavak mellé, hány szótagból állnak: víz, béka, vitorlás, nap!"),
    ("Szótag-építő", "Alkoss szavakat a szótagokból: ka + csa, bé + ka, ha + jó! Írj még egy sajátot!"),
    ("Hétvégi másolás", "Másold le szépen: Nyáron jó a vízparton játszani."),
    ("Vasárnapi mondóka", "Tanulj meg egy rövid mondókát a vízről vagy a békáról, és mondd el este a családnak!"),
    # 4. hét – elválasztás, hosszú mássalhangzók
    ("Elválasztás", "Válaszd el a szavakat: em-ber, e-gész-ség, al-ma. Írd le őket kötőjellel!"),
    ("Hosszú mássalhangzók", "Írd le és húzd alá a hosszú mássalhangzót: orra, könnyű, jobban, hallgat!"),
    ("Egy vagy kettő?", "Melyik a helyes? szeb / szebb, kissebb / kisebb, mell / mel. Írd le a jókat!"),
    ("Testrészek", "Írd le 6 testrész nevét! Szótagold is őket!"),
    ("Betűkirakó", "Milyen szó lesz belőle? z-e-m-s (szem), l-ü-f (fül), b-á-l (láb). Írd le!"),
    ("Hétvégi másolás", "Másold le szépen: A gyümölcs és a zöldség egészséges."),
    ("Vasárnapi beszélgetés", "Mesélj a családnak: mit tettél ezen a héten az egészségedért?"),
    # 5. hét – mondat, nagybetű, írásjelek
    ("A mondat", "A mondatot nagybetűvel kezdjük és írásjellel zárjuk. Írj 2 mondatot a kertről!"),
    ("Javítsd ki!", "Írd le helyesen: a virág szép   esik az eső   hol a locsolókanna"),
    ("Mondatvégi írásjelek", "Tegyél írásjelet: Milyen szép ez a rózsa_  Kérsz almát_  A répa a földben nő_"),
    ("Mondatépítő", "Rakd sorrendbe és írd le: kertben / a / virágok / nyílnak / szép"),
    ("Tulajdonnevek", "A neveket nagybetűvel írjuk. Írd le a családtagjaid nevét szépen!"),
    ("Hétvégi másolás", "Másold le szépen: Anna és Lotti almát szed a kertben."),
    ("Vasárnapi séta", "Sétáljatok egyet! Utána diktálj le valakinek 3 mondatot arról, mit láttatok."),
    # 6. hét – mondatfajták
    ("Kijelentő mondat", "A kijelentő mondat végén pont van. Írj 3 kijelentő mondatot az időjárásról!"),
    ("Kérdő mondat", "A kérdő mondat végén kérdőjel van. Írj 3 kérdést, amit egy meteorológustól kérdeznél!"),
    ("Felkiáltó mondat", "A felkiáltó mondat végén felkiáltójel van. Írj 2 felkiáltó mondatot! (Pl.: De szép a szivárvány!)"),
    ("Melyik mondatfajta?", "Írd a mondat mögé: kijelentő, kérdő vagy felkiáltó? Esik a hó. Fúj a szél? Micsoda vihar!"),
    ("Kérdezz-felelek", "Írj egy kérdést és a rá adott választ az évszakokról!"),
    ("Hétvégi másolás", "Másold le szépen: Ősszel hullanak a levelek, télen esik a hó."),
    ("Vasárnapi megfigyelés", "Figyeld meg az eget reggel, délben és este! Mondd el, mit láttál!"),
    # 7. hét – j vagy ly
    ("J vagy LY?", "Írd le: go_ó (golyó), _uk (lyuk), ha_ó (hajó), o_an (olyan)!"),
    ("LY-os szavak", "Tanuld meg: lyuk, golyó, gólya, folyó, mosolyog. Írd le mindet kétszer!"),
    ("J-s szavak", "Írd le: jármű, jegy, ajtó, fejlámpa! Húzd alá bennük a j betűt!"),
    ("Válogatás", "Csoportosítsd: hajó, gólya, jön, folyó, játék, mosoly! (J-s szavak / LY-os szavak)"),
    ("Mondatba foglalás", "Írj egy-egy mondatot ezekkel: hajó, folyó!"),
    ("Hétvégi másolás", "Másold le szépen: A hajó lassan úszik a folyón."),
    ("Vasárnapi gyűjtés", "Gyűjtsetek közösen 5 járművet, aminek a nevében j vagy ly van!"),
    # 8. hét – szókincs: ellentétek, rokon értelmű szavak
    ("Ellentétek", "Írd le a párját: nagy – ___, világos – ___, gyors – ___, meleg – ___!"),
    ("Rokon értelmű szavak", "Mondj hasonló jelentésű szót: fut (szalad...), szép, eszik! Írd le őket!"),
    ("Szócsaládok", "Gyűjts szavakat: csillag → csillagos, csillagász... Írj hármat!"),
    ("Mi a közös?", "Húzd ki a kakukktojást: Nap, Hold, csillag, autó! Miért az a kakukktojás?"),
    ("Fogalmazás-csíra", "Írj 3 mondatot arról, mit látnál egy űrhajó ablakából!"),
    ("Hétvégi másolás", "Másold le szépen: Éjjel ezer csillag ragyog az égen."),
    ("Vasárnapi csillagles", "Ha tiszta az ég, nézzétek meg este a csillagokat! Keresd meg a Holdat!"),
    # 9. hét – nagy ismétlés
    ("Nagy ismétlés 1.", "Írd le az ábécét fejből! Karikázd be benne a magánhangzókat!"),
    ("Nagy ismétlés 2.", "Írj egy kijelentő, egy kérdő és egy felkiáltó mondatot az iskoláról! Ügyelj az írásjelekre!"),
]

# Anna – környezetismeret: heti témánként 7 feladat
ANNA_KORNYEZET = [
    ["Sorolj fel 5 háziállatot és a kicsinyeik nevét! (kutya – kölyök...)",
     "Mit ad nekünk a tehén, a tyúk és a juh? Írd le!",
     "Miben különbözik a háziállat a vadállattól? Mondj 2 különbséget!",
     "Hogyan gondoskodunk egy kutyáról? Sorolj fel 4 dolgot!",
     "Melyik állat mit eszik? Kösd össze fejben: nyúl–répa, cica–?, ló–?",
     "Rajzold le a kedvenc háziállatodat, és írd mellé 3 tulajdonságát!",
     "Családi kvíz: mindenki mondjon egy háziállatos érdekességet!"],
    ["Sorolj fel 5 erdei állatot! Melyik hol lakik (odú, fészek, kotorék)?",
     "Mit gyűjt a mókus télire? Miért?",
     "Melyik állat alszik téli álmot? Írj le kettőt!",
     "Miért fontos az erdő? Mondj 3 okot!",
     "Mi a különbség a lombhullató és az örökzöld fa között?",
     "Rajzolj egy erdőt legalább 3 állattal, és nevezd meg őket!",
     "Ha kirándultok: gyűjts 3 különböző falevelet vagy tobozt!"],
    ["Sorolj fel 5 állatot, ami a vízparton él!",
     "Hogyan fejlődik a béka? Rajzold le a sorrendet: pete → ebihal → béka!",
     "Miért tud úszni a kacsa? Mi segíti?",
     "Miért fontos a víz az élőlényeknek? Mondj 3 okot!",
     "Mire kell vigyázni a vízparton? Sorolj fel 3 szabályt!",
     "Rajzolj egy tavat növényekkel és állatokkal!",
     "Kísérlet: tegyél vízbe kavicsot, parafát, kanalat! Mi úszik, mi süllyed?"],
    ["Sorold fel a fő testrészeket: fej, törzs, végtagok! Mutasd is meg!",
     "Mi az öt érzékszervünk? Melyikkel mit érzékelünk?",
     "Miért fontos a fogmosás? Hányszor mossunk fogat naponta?",
     "Melyik ételek egészségesek? Sorolj fel 5-öt!",
     "Miért fontos a mozgás és az alvás? Hány órát alszik egy gyerek?",
     "Rajzold le a tányérodat egy egészséges ebéddel!",
     "Családi torna: mindenki mutasson egy gyakorlatot, csináljátok együtt!"],
    ["Melyek a növény részei? (gyökér, szár, levél, virág, termés)",
     "Mi kell a növénynek a növekedéshez? Sorolj fel 4 dolgot!",
     "Sorolj fel 5 zöldséget és 5 gyümölcsöt!",
     "Hogyan lesz a magból növény? Meséld el sorban!",
     "Miért hasznosak a méhek? Mi történne nélkülük?",
     "Rajzolj egy virágot, és nevezd meg a részeit!",
     "Kerti munka: locsolj meg egy növényt, vagy ültess magot egy pohárba!"],
    ["Sorold fel a négy évszakot és 1-1 jellemzőjüket!",
     "Milyen időjárási jelenségeket ismersz? Sorolj fel 5-öt!",
     "Hogyan keletkezik az eső? Meséld el egyszerűen! (víz körforgása)",
     "Mikor látunk szivárványt? Sorold fel a színeit!",
     "Hogyan öltözünk télen és nyáron? Miért más?",
     "Készíts időjárás-naplót: rajzold le a mai időt (nap, felhő, eső)!",
     "Figyeld meg a felhőket! Milyen alakzatokat látsz bennük?"],
    ["Csoportosítsd a járműveket: szárazföldi, vízi, légi! Írj 2-2 példát!",
     "Mit jelentenek a közlekedési lámpa színei?",
     "Hogyan kelünk át biztonságosan az úttesten? Sorold el a lépéseket!",
     "Melyik járművek segítenek a bajban? (mentő, tűzoltó, rendőr) Mi a hívószámuk? (112)",
     "Miért egészséges a biciklizés? Mi kell hozzá a fejedre?",
     "Rajzolj egy közlekedési táblát, és mondd el, mit jelent!",
     "Séta közben számoljátok meg, hány piros autót láttok!"],
    ["Mi a különbség a Nap, a Hold és a csillagok között?",
     "Miért van nappal és éjszaka? (A Föld forog!)",
     "Sorold fel, mit tudsz a Földről! Milyen alakú? Mi borítja?",
     "Ki volt az első ember a Holdon? Nézzetek utána együtt!",
     "Miért kell vigyáznunk a Földre? Mondj 3 dolgot, amit te is megtehetsz!",
     "Rajzold le a Napot, a Földet és a Holdat! Melyik a legnagyobb?",
     "Esti program: keressétek meg az égen a Holdat! Milyen alakú ma?"],
    ["Ismétlés: sorolj fel 3 háziállatot, 3 erdei és 3 vízparti állatot!",
     "Ismétlés: mondd el, mit viszel magaddal az iskolába, és miért!"],
]

# Anna – szöveges feladat sablonok (heti témához {a}, {b} számokkal)
ANNA_SZOVEGES = [
    "A tanyán {a} tyúk és {b} kacsa él. Hány szárnyas van összesen?",
    "Az erdőben {a} mókus gyűjt makkot. {b} mókus hazaszalad. Hány mókus marad?",
    "A tóban {a} béka brekeg, majd odaugrik még {b}. Hány béka brekeg most?",
    "Anna {a} percet fogmosással, {b} percet tornával tölt. Hány perc ez összesen?",
    "A kertben {a} szál virág nyílik, leszedünk {b} szálat. Hány szál marad?",
    "Hétfőn {a} mm eső esett, kedden {b} mm. Hány mm esett a két napon?",
    "A parkolóban {a} autó áll, elmegy {b}. Hány autó marad?",
    "Az égen {a} csillagot számoltunk, majd még {b}-t. Hány csillagot láttunk?",
    "Az osztályba {a} gyerek jár, {b} gyerek hiányzik. Hányan vannak jelen?",
]

# Lotti – mondókák (magyar népi mondókák, közkincs)
LOTTI_MONDOKAK = [
    "Csiga-biga, gyere ki! (Mutasd az ujjaddal a csiga szarvát!)",
    "Ecc-pecc, kimehetsz! (Számoljátok ki, ki lesz a fogó!)",
    "Katalinka, szállj el! (Engedj el egy képzeletbeli katicát!)",
    "Süss fel, nap! (Tárd szét a karod, mint a napsugár!)",
    "Gólya, gólya, gilice! (Állj fél lábon, mint a gólya!)",
    "Hinta-palinta! (Hintázz a mondóka ritmusára!)",
    "Zsipp-zsupp, kenderzsupp! (Hintáztassátok a plüssmacit!)",
    "Egy – megérett a meggy! (Számolj az ujjaidon tízig!)",
    "Ez elment vadászni! (Sorold az ujjaidon!)",
    "Kerekecske, gombocska! (Rajzolj kört a tenyeredbe!)",
    "Töröm, töröm a mákot! (Utánozd a mozdulatot!)",
    "Esik az eső, hajlik a vessző! (Dobold az ujjaiddal az esőt!)",
]

# Lotti – finommotorika feladatok (rajzos vonalvezetéshez szöveg)
LOTTI_MOTOROS = [
    "Kösd össze a pontozott vonalat az ujjaddal, majd ceruzával is!",
    "Rajzold át a hullámvonalat, mintha a halacska úszna!",
    "Kövesd a cikkcakk vonalat – ez a sün tüskéje!",
    "Rajzold körbe a kört háromszor, el ne hagyd az utat!",
    "Húzz egyenes vonalat – ezen gurul az autó!",
]

# Lotti – színek és formák heti forgásban
LOTTI_SZINEK = ["piros", "kék", "sárga", "zöld", "narancssárga", "lila", "rózsaszín", "barna", "fehér"]
LOTTI_FORMAK = ["kör", "négyzet", "háromszög", "csillag", "szív"]

# Lotti – betűk (játékos hangfelismerés)
LOTTI_BETUK = ["A", "E", "I", "O", "U", "M", "S", "L", "P", "T", "K", "B", "C", "D", "F", "G", "H", "N", "R", "V", "Z", "J"]

# Óraolvasás progresszió heti bontásban (Anna)
ORA_HETEK = [
    ("egész órák", [(h, 0) for h in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)]),
    ("fél órák", [(h, 30) for h in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)]),
    ("negyed és háromnegyed", [(h, m) for h in (1, 3, 5, 7, 9, 11) for m in (15, 45)]),
    ("egész, fél, negyed vegyesen", [(h, m) for h in (2, 4, 6, 8, 10, 12) for m in (0, 15, 30, 45)]),
    ("percek 5-ösével", [(h, m) for h in (1, 4, 7, 10) for m in (5, 10, 20, 25)]),
    ("percek 5-ösével (nehezebb)", [(h, m) for h in (2, 5, 8, 11) for m in (35, 40, 50, 55)]),
    ("digitális és analóg", [(h, m) for h in (3, 6, 9, 12) for m in (10, 25, 40, 55)]),
    ("vegyes ismétlés", [(h, m) for h in (1, 5, 9) for m in (0, 15, 30, 45, 20)]),
    ("nagy óra-ismétlés", [(7, 45), (8, 0), (12, 30), (16, 15), (18, 50)]),
]
